export const UPDATESCHOOLLIST = "UPDATESCHOOLLIST";
export const UPDATE_CITYS_LIST = "UPDATE_CITYS_LIST";
export const UPDATE_TAGS_LIST = "UPDATE_TAGS_LIST"

export const DATAS_ERROR = "DATAS_ERROR";
export const DATAS_CLEARTYPE = "DATAS_CLEARTYPE";
