export const UPDATER_HISTORY_LIST = "UPDATER_HISTORY_LIST";
export const UPDATE_CURRENT_HISTORY = "UPDATE_CURRENT_HISTORY";
export const HISTORY_ERROR = "HISTORY_ERROR";
export const HISTORY_CLEARTYPE = "HISTORY_CLEARTYPE";
