export const UPDATE_USERPROFILE = "UPDATE_USERPROFILE";
export const UPDATE_USERINFOFROMDB = "UPDATE_USERINFOFROMDB";
export const UPDATEACCESSTOKEN = "UPDATEACCESSTOKEN";
export const SUBMITUSERINFOTODB = "SUBMITUSERINFOTODB";
export const CLEARTYPE = "CLEARTYPE";
