export const UPDATE_USERPROFILE = "UPDATE_USERPROFILE";
export const UPDATE_USERINFOFROMDB = "UPDATE_USERINFOFROMDB";
export const UPDATEACCESSTOKEN = "UPDATEACCESSTOKEN";
export const SUBMITUSERINFOTODB = "SUBMITUSERINFOTODB";
export const UPDATE_USERINFOEDIT = "UPDATE_USERINFOEDIT";
export const RESET_USERINFOEDIT = "RESET_USERINFOEDIT";
export const UPDATE_USERINFOEDITTIPS = "UPDATE_USERINFOEDITTIPS";
export const UPDATE_USERFILE = "UPDATE_USERFILE";
export const DELETE_USERFILE = "DELETE_USERFILE";
export const GET_USERFILES = "GET_USERFILES";
export const UPDATE_USERPRODUCTION = "UPDATE_USERPRODUCTION";
export const DELETE_USERPRODUCTION = "DELETE_USERPRODUCTION";
export const GET_USERPRODUCTIONS = "GET_USERPRODUCTIONS";

export const USER_ERROR = "USER_ERROR";
export const USER_CLEARTYPE = "USER_CLEARTYPE";
